### ISSUE TITLE
I found this

### ISSUE THREAD

**Issue by Drakaroft** [hgabor/kfirpgcreator#1]
Hi i found this and seems cool, but i see that it is stuck. Any intent to restart making this? It seems interesting

**Comment by hgabor** [comment]
Hi!
Thanks for the interest, but as I said in the description, I consider this project abandoned. Feel free to fork it, if you like.

**Comment by Drakaroft** [comment]
Hi! sorry i didn't see the that part in the description. I would give it a try! But i fall compiling with vs2017...
